# Generated by Django 5.2.8 on 2025-11-17 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_herocontent_heroslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='herocontent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='hero_single/'),
        ),
    ]
