# Generated by Django 5.2.8 on 2025-11-17 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_herocontent_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeTwoHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField()),
                ('card_title', models.CharField(max_length=200)),
                ('card_text', models.CharField(max_length=300)),
                ('video', models.FileField(blank=True, null=True, upload_to='home2_hero/')),
            ],
        ),
        migrations.RemoveField(
            model_name='herocontent',
            name='video',
        ),
    ]
