# Generated by Django 5.2.8 on 2025-11-17 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_hometwohero_remove_herocontent_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeThreeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('subtitle', models.TextField()),
                ('button1_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button1_link', models.CharField(blank=True, max_length=300, null=True)),
                ('button2_text', models.CharField(blank=True, max_length=100, null=True)),
                ('button2_link', models.CharField(blank=True, max_length=300, null=True)),
                ('video', models.FileField(blank=True, null=True, upload_to='home3_hero/')),
            ],
        ),
    ]
